<?php

namespace Proxies\__CG__\power\genBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Owner extends \power\genBundle\Entity\Owner implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setRegisterDate($registerDate)
    {
        $this->__load();
        return parent::setRegisterDate($registerDate);
    }

    public function getRegisterDate()
    {
        $this->__load();
        return parent::getRegisterDate();
    }

    public function setRegisterNumber($registerNumber)
    {
        $this->__load();
        return parent::setRegisterNumber($registerNumber);
    }

    public function getRegisterNumber()
    {
        $this->__load();
        return parent::getRegisterNumber();
    }

    public function setBirthDay($birthDay)
    {
        $this->__load();
        return parent::setBirthDay($birthDay);
    }

    public function getBirthDay()
    {
        $this->__load();
        return parent::getBirthDay();
    }

    public function setNationality($nationality)
    {
        $this->__load();
        return parent::setNationality($nationality);
    }

    public function getNationality()
    {
        $this->__load();
        return parent::getNationality();
    }

    public function setIdCard($idCard)
    {
        $this->__load();
        return parent::setIdCard($idCard);
    }

    public function getIdCard()
    {
        $this->__load();
        return parent::getIdCard();
    }

    public function setDistrictOfIssue($districtOfIssue)
    {
        $this->__load();
        return parent::setDistrictOfIssue($districtOfIssue);
    }

    public function getDistrictOfIssue()
    {
        $this->__load();
        return parent::getDistrictOfIssue();
    }

    public function setProviceOfIssue($proviceOfIssue)
    {
        $this->__load();
        return parent::setProviceOfIssue($proviceOfIssue);
    }

    public function getProviceOfIssue()
    {
        $this->__load();
        return parent::getProviceOfIssue();
    }

    public function setAdressNumber($adressNumber)
    {
        $this->__load();
        return parent::setAdressNumber($adressNumber);
    }

    public function getAdressNumber()
    {
        $this->__load();
        return parent::getAdressNumber();
    }

    public function setLane($lane)
    {
        $this->__load();
        return parent::setLane($lane);
    }

    public function getLane()
    {
        $this->__load();
        return parent::getLane();
    }

    public function setStreet($street)
    {
        $this->__load();
        return parent::setStreet($street);
    }

    public function getStreet()
    {
        $this->__load();
        return parent::getStreet();
    }

    public function setVillageNumber($villageNumber)
    {
        $this->__load();
        return parent::setVillageNumber($villageNumber);
    }

    public function getVillageNumber()
    {
        $this->__load();
        return parent::getVillageNumber();
    }

    public function setSubDistrict($subDistrict)
    {
        $this->__load();
        return parent::setSubDistrict($subDistrict);
    }

    public function getSubDistrict()
    {
        $this->__load();
        return parent::getSubDistrict();
    }

    public function setDistrict($district)
    {
        $this->__load();
        return parent::setDistrict($district);
    }

    public function getDistrict()
    {
        $this->__load();
        return parent::getDistrict();
    }

    public function setProvince($province)
    {
        $this->__load();
        return parent::setProvince($province);
    }

    public function getProvince()
    {
        $this->__load();
        return parent::getProvince();
    }

    public function setPoscode($poscode)
    {
        $this->__load();
        return parent::setPoscode($poscode);
    }

    public function getPoscode()
    {
        $this->__load();
        return parent::getPoscode();
    }

    public function setTelNumber($telNumber)
    {
        $this->__load();
        return parent::setTelNumber($telNumber);
    }

    public function getTelNumber()
    {
        $this->__load();
        return parent::getTelNumber();
    }

    public function setFaxNumber($faxNumber)
    {
        $this->__load();
        return parent::setFaxNumber($faxNumber);
    }

    public function getFaxNumber()
    {
        $this->__load();
        return parent::getFaxNumber();
    }

    public function setIscorp($iscorp)
    {
        $this->__load();
        return parent::setIscorp($iscorp);
    }

    public function getIscorp()
    {
        $this->__load();
        return parent::getIscorp();
    }

    public function setMobilePhone($mobilePhone)
    {
        $this->__load();
        return parent::setMobilePhone($mobilePhone);
    }

    public function getMobilePhone()
    {
        $this->__load();
        return parent::getMobilePhone();
    }

    public function setWebsite($website)
    {
        $this->__load();
        return parent::setWebsite($website);
    }

    public function getWebsite()
    {
        $this->__load();
        return parent::getWebsite();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function addEstablishment(\power\genBundle\Entity\Establishment $establishments)
    {
        $this->__load();
        return parent::addEstablishment($establishments);
    }

    public function removeEstablishment(\power\genBundle\Entity\Establishment $establishments)
    {
        $this->__load();
        return parent::removeEstablishment($establishments);
    }

    public function getEstablishments()
    {
        $this->__load();
        return parent::getEstablishments();
    }

    public function setOwnertype(\power\genBundle\Entity\Ownertype $ownertype = NULL)
    {
        $this->__load();
        return parent::setOwnertype($ownertype);
    }

    public function getOwnertype()
    {
        $this->__load();
        return parent::getOwnertype();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'name', 'registerDate', 'registerNumber', 'birthDay', 'nationality', 'idCard', 'districtOfIssue', 'proviceOfIssue', 'adressNumber', 'lane', 'street', 'villageNumber', 'subDistrict', 'district', 'province', 'poscode', 'telNumber', 'faxNumber', 'iscorp', 'mobilePhone', 'website', 'email', 'id', 'establishments', 'ownertype');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}