parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: '3306'
    database_name: powergenthailand_dev
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 0b831239511e47c037c12e74bdd6635ca85ebf00
    database_path: null
