<?php

namespace power\genBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PowerengineDieselController__JMSInjector
{
    public static function inject($container) {
        $instance = new \power\genBundle\Controller\PowerengineDieselController();
        return $instance;
    }
}
